<?php
	/***********************************************************************************************************
		* Author Name 		: Gagandeep Kaur
		* Creation Date 	: 13 June-2006
		* FileName 			: functions.php	
		* Called From		: All the controller file.
		* Description 		: Contains all the common functions used on the site.
		* Components Used 	: none
		* Tables Accessed 	: none
		* Program Specs 	:  
		* UTP doc 			:
		* Tested By 		:
	************************************************************************************************************/
		
	require_once($_CONF['ModulesPath'].'system/classes/extra/class.phpmailer.php');					
	require_once($_CONF['LibPath'].'mail/htmlMimeMail.php');	//this class is used to compose and send mails in HTML format
	require_once($_CONF['LibPath'].'mail/SendEmail.php');
	
		
	/***************************************************************************************
	*Function Header
	*Function Name  : SendMail
	*Function Type  : call by value
	*Functionality  : Sends mail in HTML or text format
	*Input			: body,subject,to,from and format of the email
	*Output			: mail sent in HTML or Text format
	*Return Value   : boolear value of True or False depending whether mail is sent or not
	*Note			: nothing
	****************************************************************************************/
	function SendMail($msg, $subject, $toEmails = array(), $from, $isHtml=1,$file="",$bcc="",$cand_name="",$cc="")
	{
		
		global $error;	
		global $_CONF;		
		
				
		$mail->From 	= $from;
		$mail->FromName = "VOICES FOR CHANGE";
		$from_name = "VOICES FOR CHANGE";
		
		$mail = new PHPMailer();  // create a new object
		$mail->IsSMTP(); // enable SMTP
		$mail->IsHTML(); // enable SMTP
		
		$mail->SMTPDebug = 1;  // debugging: 1 = errors and messages, 2 = messages only
		$mail->SMTPAuth = true;  // authentication enabled
		//$mail->SMTPSecure = 'ssl'; // secure transfer enabled REQUIRED for Gmail
		
		$mail->Host = SMTP_HOST;
		$mail->Port = SMTP_PORT; 
		$mail->Username = SMTP_USERNAME;  
		$mail->Password = SMTP_PASSWORD;  
		
		$mail->SetFrom($from, $from_name);
		$mail->Body    = $msg;
		$mail->Subject  = $subject;	
		
		$to =  $toEmails[0]; 
		if(trim($to) != "") {
			$mail->AddAddress($to);
		}
		
		$bcc =  $bcc[0];
		if(trim($bcc) != "") {
			$mail->AddBCC($bcc);
		}
		
		$cc =  $cc[0];
		if(trim($cc) != "") {
			$mail->AddCC($cc);
		}
		
		if(trim($file) != "") {
			$mail->AddAttachment($file);
		}
		
		if(!$mail->Send()) {				
			return false;
		} else {
			return true;
		}
     }
	/***************************************************************************************
	*Function Header
	*Function Name  : SendMailBuy
	*Function Type  : call by value
	*Functionality  : Sends mail in HTML or text format and attach the attachment
	*Input			: body,subject,to,from,attachment name,attachment path and format of the email
	*Output			: mail sent in HTML or Text format
	*Return Value   : boolear value of True or False depending whether mail is sent or not
	*Note			: nothing
	****************************************************************************************/
	function SendMailBuy($body, $subject,$toEmails = array(),$attachment_name="", $attachment="", $fromEmail = "", $format = "HTML")
	{
		global $_CONF;
		
		$html	=	$body;
		$oMail	=	new htmlMimeMail();
		$oMail->setHtml($html, $body, './');
		$oMail->setSubject($subject);
	 	$file =$oMail->getFile($attachment);
		$oMail->addAttachment($file,$attachment_name);
		
		$result	=	$oMail->send($toEmails);
		return $result;
	}
		

	/***************************************************************************************
	*Function Header
	*Function Name  : CreateMailMessage
	*Function Type  : call by value
	*Functionality  : Creates and format a mail message depending on event for which mail has to be 
					  sent. All autogenerated and other mails format is set here.
	*Input			: mode containing type of mail message to be generated and some 
					  dynamic info if needed
	*Output			: created mail in text or HTML format
	*Return Value   : mail info array  containing all the mail content
	*Note			: nothing
	****************************************************************************************/
		
	function CreateMailMessage1($mode, $dynamicInfo = array()){
		global $_CONF;
		$mailInfo['body']		=	"";
		$mailInfo['subject']	=	"";
	}
	
	function CreateMailMessage($body)
	{
		global $_CONF;
		$mailInfo['body']		=	nl2br($body);
		return $mailInfo;
	}

		if ( !function_exists('htmlspecialchars_decode') )
		{
			function htmlspecialchars_decode($text)
			{
				return strtr($text, array_flip(get_html_translation_table(HTML_SPECIALCHARS)));
			}
		}

	function sendMailAtt($to, $from, $subject, $msg, $isHtml=1,$file)
	{
		$mail = new PHPMailer();
		$mail->From   = $from;
		$mail->FromName = "Bohire";
		$mail->Body    = $msg;
		$mail->Subject  = $subject;
		$mail->AddAddress($to);
		$mail->AddAttachment($file);
		
		if(!$mail->Send()) {
			return $mail->ErrorInfo;
		} else {
			return 0;
		}
	}

	
	//****************function to generate random password****************************//
	function generateRandStr()
	{
		global $_CONF;
		$length	=	$_CONF['RandomStringLength'];
		$randstr = "";
		for($i=0; $i<$length; $i++)
		{
			$num	=	rand(1,2);
			if(1==$num)
			{
				$randnum = mt_rand(0,61);
				if($randnum < 10)
				{
					$randstr .= chr($randnum+48);
				}
				elseif($randnum < 36)
				{
					$randstr .= chr($randnum+55);
				}
				else
				{
					$randstr .= chr($randnum+61);
				}
			}
			else
			{
				$randnum = mt_rand(48,57);
				$randstr .= chr($randnum);
			}
		}
		return $randstr;
	}
?>